// lang.js
export const translations = {
    en: {
        welcome: "Welcome!",
        coj: "Create or Join",
        yourName: "Your Name",
        createGame: "Create New Game",
        or: "OR",
        gameCode: "Game Code",
        joinGame: "Join with Code",
        loading: "Loading Game...",
        noPlayers: "No Players yet",
        lobby: "Lobby",
        shareCode: "Share this code with your friends to join the game",
        waitingForHostText: "Waiting for the Lobby Host to start the game.",
        startGame: "Start Game",
        youAreTheHost: "You are the host",
        givePrompt: "Give a prompt to the players",
        setTheme: "Set a theme",
        waitingForTheme: "Waiting for ${hostName} to set a theme...",
        themeSet: "Theme: '${data.theme}'",
        waitingForSubmit: "Waiting for players to submit their images...",
        submit: "${submittedPlayers} / ${totalPlayers} submitted",
        submitted: "You submitted your image, waiting for others...",
        submitBtn: "Submit Image",
        guessWho: "Guess Who submitted this image",
        pSelect: "select a player",
        lockIn: "Lock in your guess",
        guessing: "${hostName} is guessing...",
        rate: "waiting for players to rate the images",
        rated: "Thank's for rating!",
        youRate: "Rate your favorite image",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "CORRECT",
        nah: "WRONG",
        submitRatings: "Submit Ratings",
        calculateScores: "Calculate Scores",
        over: "Round Over",
        finalScores: "Final Scores",
        playAgain: "Play again",
        waitingFHTS: "Waiting for ${hostName} to start the next round...",
    },
    pl: {
        welcome: "Witamy!",
        coj: "Utwórz lub Dołącz",
        yourName: "Twoje imię",
        createGame: "Utwórz nową grę",
        or: "LUB",
        gameCode: "Kod gry",
        joinGame: "Dołącz za pomocą kodu",
        loading: "Ładowanie gry...",
        noPlayers: "Brak graczy jeszcze",
        lobby: "Poczekalnia",
        shareCode: "Udostępnij ten kod znajomym, aby dołączyć do gry",
        waitingForHostText: "Czekam na hosta poczekalni, aby rozpocząć grę.",
        startGame: "Rozpocznij grę",
        youAreTheHost: "Jesteś hostem",
        givePrompt: "Podaj temat graczom",
        setTheme: "Ustaw motyw",
        waitingForTheme: "Czekam na ${hostName}, aby ustawił motyw...",
        themeSet: "Motyw: '${data.theme}'",
        waitingForSubmit: "Czekam, aż gracze prześlą swoje obrazy...",
        submit: "${submittedPlayers} / ${totalPlayers} przesłanych",
        submitted: "Przesłałeś swój obraz, czekam na innych...",
        submitBtn: "Prześlij obraz",
        guessWho: "Zgadnij, kto przesłał ten obraz",
        pSelect: "wybierz gracza",
        lockIn: "Zablokuj swoje zgadywanie",
        guessing: "${hostName} zgaduje...",
        rate: "Czekam, aż gracze ocenią obrazy",
        rated: "Dzięki za ocenę!",
        youRate: "Oceń swój ulubiony obraz",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "POPRAWNIE",
        nah: "ŹLE",
        submitRatings: "Prześlij oceny",
        calculateScores: "Oblicz wyniki",
        over: "Runda zakończona",
        finalScores: "Wyniki końcowe",
        playAgain: "Zagraj ponownie",
        waitingFHTS: "Czekam na ${hostName}, aby rozpoczął następną rundę...",
    },
    mc: { // Assuming 'mc' is simplified Chinese
        welcome: "欢迎！",
        coj: "创建或加入",
        yourName: "你的名字",
        createGame: "创建新游戏",
        or: "或",
        gameCode: "游戏代码",
        joinGame: "使用代码加入",
        loading: "正在加载游戏...",
        noPlayers: "还没有玩家",
        lobby: "大厅",
        shareCode: "与你的朋友分享此代码以加入游戏",
        waitingForHostText: "等待大厅主持人开始游戏。",
        startGame: "开始游戏",
        youAreTheHost: "你是主持人",
        givePrompt: "给玩家一个提示",
        setTheme: "设置主题",
        waitingForTheme: "等待 ${hostName} 设置主题...",
        themeSet: "主题: '${data.theme}'",
        waitingForSubmit: "等待玩家提交他们的图片...",
        submit: "${submittedPlayers} / ${totalPlayers} 已提交",
        submitted: "您已提交您的图片，等待其他人...",
        submitBtn: "提交图片",
        guessWho: "猜猜谁提交了这张图片",
        pSelect: "选择一个玩家",
        lockIn: "锁定你的猜测",
        guessing: "${hostName} 正在猜测...",
        rate: "等待玩家评价图片",
        rated: "感谢您的评价！",
        youRate: "评价您最喜欢的图片",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "正确",
        nah: "错误",
        submitRatings: "提交评分",
        calculateScores: "计算分数",
        over: "回合结束",
        finalScores: "最终得分",
        playAgain: "再玩一次",
        waitingFHTS: "等待 ${hostName} 开始下一轮...",
    },
    es: {
        welcome: "¡Bienvenido!",
        coj: "Crear o Unirse",
        yourName: "Tu Nombre",
        createGame: "Crear Nuevo Juego",
        or: "O",
        gameCode: "Código del Juego",
        joinGame: "Unirse con Código",
        loading: "Cargando Juego...",
        noPlayers: "Aún no hay jugadores",
        lobby: "Vestíbulo",
        shareCode: "Comparte este código con tus amigos para unirte al juego",
        waitingForHostText: "Esperando a que el Anfitrión del Vestíbulo inicie el juego.",
        startGame: "Iniciar Juego",
        youAreTheHost: "Eres el anfitrión",
        givePrompt: "Da una pista a los jugadores",
        setTheme: "Establecer un tema",
        waitingForTheme: "Esperando a que ${hostName} establezca un tema...",
        themeSet: "Tema: '${data.theme}'",
        waitingForSubmit: "Esperando a que los jugadores envíen sus imágenes...",
        submit: "${submittedPlayers} / ${totalPlayers} enviados",
        submitted: "Enviaste tu imagen, esperando a los demás...",
        submitBtn: "Enviar Imagen",
        guessWho: "Adivina quién envió esta imagen",
        pSelect: "seleccionar un jugador",
        lockIn: "Confirmar tu suposición",
        guessing: "${hostName} está adivinando...",
        rate: "esperando a que los jugadores califiquen las imágenes",
        rated: "¡Gracias por calificar!",
        youRate: "Califica tu imagen favorita",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "CORRECTO",
        nah: "INCORRECTO",
        submitRatings: "Enviar Calificaciones",
        calculateScores: "Calcular Puntuaciones",
        over: "Ronda Terminada",
        finalScores: "Puntuaciones Finales",
        playAgain: "Jugar de nuevo",
        waitingFHTS: "Esperando a ${hostName} para iniciar la siguiente ronda...",
    },
    de: {
        welcome: "Willkommen!",
        coj: "Erstellen oder Beitreten",
        yourName: "Dein Name",
        createGame: "Neues Spiel Erstellen",
        or: "ODER",
        gameCode: "Spielcode",
        joinGame: "Mit Code Beitreten",
        loading: "Spiel wird geladen...",
        noPlayers: "Noch keine Spieler",
        lobby: "Lobby",
        shareCode: "Teile diesen Code mit deinen Freunden, um dem Spiel beizutreten",
        waitingForHostText: "Warte auf den Lobby-Host, um das Spiel zu starten.",
        startGame: "Spiel starten",
        youAreTheHost: "Du bist der Host",
        givePrompt: "Gib den Spielern eine Eingabeaufforderung",
        setTheme: "Ein Thema festlegen",
        waitingForTheme: "Warte auf ${hostName}, um ein Thema festzulegen...",
        themeSet: "Thema: '${data.theme}'",
        waitingForSubmit: "Warte auf Spieler, die ihre Bilder einreichen...",
        submit: "${submittedPlayers} / ${totalPlayers} eingereicht",
        submitted: "Du hast dein Bild eingereicht, warte auf andere...",
        submitBtn: "Bild einreichen",
        guessWho: "Rate, wer dieses Bild eingereicht hat",
        pSelect: "einen Spieler auswählen",
        lockIn: "Deine Vermutung festlegen",
        guessing: "${hostName} rät...",
        rate: "warte darauf, dass Spieler die Bilder bewerten",
        rated: "Danke fürs Bewerten!",
        youRate: "Bewerte dein Lieblingsbild",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "KORREKT",
        nah: "FALSCH",
        submitRatings: "Bewertungen einreichen",
        calculateScores: "Punkte berechnen",
        over: "Runde vorbei",
        finalScores: "Endergebnisse",
        playAgain: "Nochmal spielen",
        waitingFHTS: "Warte auf ${hostName}, um die nächste Runde zu starten...",
    },
    fr: {
        welcome: "Bienvenue!",
        coj: "Créer ou Rejoindre",
        yourName: "Votre Nom",
        createGame: "Créer un Nouveau Jeu",
        or: "OU",
        gameCode: "Code du Jeu",
        joinGame: "Rejoindre avec le Code",
        loading: "Chargement du Jeu...",
        noPlayers: "Pas encore de joueurs",
        lobby: "Salon",
        shareCode: "Partagez ce code avec vos amis pour rejoindre la partie",
        waitingForHostText: "En attente de l'hôte du salon pour démarrer la partie.",
        startGame: "Démarrer la partie",
        youAreTheHost: "Vous êtes l'hôte",
        givePrompt: "Donnez une consigne aux joueurs",
        setTheme: "Définir un thème",
        waitingForTheme: "En attente de ${hostName} pour définir un thème...",
        themeSet: "Thème: '${data.theme}'",
        waitingForSubmit: "En attente que les joueurs soumettent leurs images...",
        submit: "${submittedPlayers} / ${totalPlayers} soumis",
        submitted: "Vous avez soumis votre image, en attente des autres...",
        submitBtn: "Soumettre l'image",
        guessWho: "Devinez qui a soumis cette image",
        pSelect: "sélectionner un joueur",
        lockIn: "Confirmer votre supposition",
        guessing: "${hostName} est en train de deviner...",
        rate: "en attente que les joueurs évaluent les images",
        rated: "Merci pour votre évaluation !",
        youRate: "Évaluez votre image préférée",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "CORRECT",
        nah: "FAUX",
        submitRatings: "Soumettre les évaluations",
        calculateScores: "Calculer les scores",
        over: "Manche terminée",
        finalScores: "Scores finaux",
        playAgain: "Rejouer",
        waitingFHTS: "En attente de ${hostName} pour démarrer la prochaine manche...",
    },
    it: {
        welcome: "Benvenuto!",
        coj: "Crea o Unisciti",
        yourName: "Il Tuo Nome",
        createGame: "Crea Nuova Partita",
        or: "O",
        gameCode: "Codice della Partita",
        joinGame: "Unisciti con Codice",
        loading: "Caricamento della Partita...",
        noPlayers: "Nessun giocatore ancora",
        lobby: "Lobby",
        shareCode: "Condividi questo codice con i tuoi amici per unirti alla partita",
        waitingForHostText: "In attesa che l'Host della Lobby avvii la partita.",
        startGame: "Avvia Partita",
        youAreTheHost: "Sei l'host",
        givePrompt: "Dai un suggerimento ai giocatori",
        setTheme: "Imposta un tema",
        waitingForTheme: "In attesa che ${hostName} imposti un tema...",
        themeSet: "Tema: '${data.theme}'",
        waitingForSubmit: "In attesa che i giocatori inviino le loro immagini...",
        submit: "${submittedPlayers} / ${totalPlayers} inviati",
        submitted: "Hai inviato la tua immagine, in attesa degli altri...",
        submitBtn: "Invia Immagine",
        guessWho: "Indovina chi ha inviato questa immagine",
        pSelect: "seleziona un giocatore",
        lockIn: "Conferma la tua ipotesi",
        guessing: "${hostName} sta indovinando...",
        rate: "in attesa che i giocatori valutino le immagini",
        rated: "Grazie per aver votato!",
        youRate: "Vota la tua immagine preferita",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "CORRETTO",
        nah: "SBAGLIATO",
        submitRatings: "Invia Valutazioni",
        calculateScores: "Calcola Punteggi",
        over: "Round Terminato",
        finalScores: "Punteggi Finali",
        playAgain: "Gioca di nuovo",
        waitingFHTS: "In attesa che ${hostName} avvii il prossimo round...",
    },
    pt: {
        welcome: "Bem-vindo!",
        coj: "Criar ou Juntar-se",
        yourName: "Seu Nome",
        createGame: "Criar Novo Jogo",
        or: "OU",
        gameCode: "Código do Jogo",
        joinGame: "Juntar-se com Código",
        loading: "Carregando Jogo...",
        noPlayers: "Nenhum jogador ainda",
        lobby: "Lobby",
        shareCode: "Compartilhe este código com seus amigos para entrar no jogo",
        waitingForHostText: "Aguardando o Anfitrião do Lobby iniciar o jogo.",
        startGame: "Iniciar Jogo",
        youAreTheHost: "Você é o anfitrião",
        givePrompt: "Dê uma sugestão aos jogadores",
        setTheme: "Definir um tema",
        waitingForTheme: "Aguardando ${hostName} definir um tema...",
        themeSet: "Tema: '${data.theme}'",
        waitingForSubmit: "Aguardando os jogadores enviarem suas imagens...",
        submit: "${submittedPlayers} / ${totalPlayers} enviados",
        submitted: "Você enviou sua imagem, aguardando outros...",
        submitBtn: "Enviar Imagem",
        guessWho: "Adivinhe quem enviou esta imagem",
        pSelect: "selecionar um jogador",
        lockIn: "Confirmar seu palpite",
        guessing: "${hostName} está adivinhando...",
        rate: "aguardando os jogadores avaliarem as imagens",
        rated: "Obrigado por avaliar!",
        youRate: "Avalie sua imagem favorita",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "CORRETO",
        nah: "ERRADO",
        submitRatings: "Enviar Avaliações",
        calculateScores: "Calcular Pontuações",
        over: "Rodada Encerrada",
        finalScores: "Pontuações Finais",
        playAgain: "Jogar novamente",
        waitingFHTS: "Aguardando ${hostName} iniciar a próxima rodada...",
    },
    ru: {
        welcome: "Добро пожаловать!",
        coj: "Создать или Присоединиться",
        yourName: "Ваше Имя",
        createGame: "Создать Новую Игру",
        or: "ИЛИ",
        gameCode: "Код Игры",
        joinGame: "Присоединиться по Коду",
        loading: "Загрузка Игры...",
        noPlayers: "Пока нет игроков",
        lobby: "Лобби",
        shareCode: "Поделитесь этим кодом с друзьями, чтобы присоединиться к игре",
        waitingForHostText: "Ожидание, пока Хост Лобби начнет игру.",
        startGame: "Начать игру",
        youAreTheHost: "Вы хост",
        givePrompt: "Дайте подсказку игрокам",
        setTheme: "Установить тему",
        waitingForTheme: "Ожидание, пока ${hostName} установит тему...",
        themeSet: "Тема: '${data.theme}'",
        waitingForSubmit: "Ожидание, пока игроки отправят свои изображения...",
        submit: "${submittedPlayers} / ${totalPlayers} отправлено",
        submitted: "Вы отправили свое изображение, ожидание остальных...",
        submitBtn: "Отправить изображение",
        guessWho: "Угадайте, кто отправил это изображение",
        pSelect: "выбрать игрока",
        lockIn: "Зафиксировать свою догадку",
        guessing: "${hostName} угадывает...",
        rate: "ожидание, пока игроки оценят изображения",
        rated: "Спасибо за оценку!",
        youRate: "Оцените ваше любимое изображение",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "ВЕРНО",
        nah: "НЕВЕРНО",
        submitRatings: "Отправить оценки",
        calculateScores: "Подсчитать очки",
        over: "Раунд окончен",
        finalScores: "Финальные очки",
        playAgain: "Играть снова",
        waitingFHTS: "Ожидание, пока ${hostName} начнет следующий раунд...",
    },
    tr: {
        welcome: "Hoş geldiniz!",
        coj: "Oluştur veya Katıl",
        yourName: "Adınız",
        createGame: "Yeni Oyun Oluştur",
        or: "VEYA",
        gameCode: "Oyun Kodu",
        joinGame: "Koda Göre Katıl",
        loading: "Oyun Yükleniyor...",
        noPlayers: "Henüz oyuncu yok",
        lobby: "Lobi",
        shareCode: "Oyuna katılmak için bu kodu arkadaşlarınızla paylaşın",
        waitingForHostText: "Lobi Sunucusunun oyunu başlatması bekleniyor.",
        startGame: "Oyunu Başlat",
        youAreTheHost: "Siz sunucusunuz",
        givePrompt: "Oyunculara bir ipucu verin",
        setTheme: "Bir tema belirle",
        waitingForTheme: "${hostName} temasını belirlemesi bekleniyor...",
        themeSet: "Tema: '${data.theme}'",
        waitingForSubmit: "Oyuncuların görsellerini göndermesi bekleniyor...",
        submit: "${submittedPlayers} / ${totalPlayers} gönderildi",
        submitted: "Görselinizi gönderdiniz, diğerleri bekleniyor...",
        submitBtn: "Görsel Gönder",
        guessWho: "Bu görseli kimin gönderdiğini tahmin et",
        pSelect: "bir oyuncu seç",
        lockIn: "Tahmininizi kilitleyin",
        guessing: "${hostName} tahmin ediyor...",
        rate: "oyuncuların görselleri değerlendirmesi bekleniyor",
        rated: "Derecelendirme için teşekkürler!",
        youRate: "Favori görselinizi derecelendirin",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "DOĞRU",
        nah: "YANLIŞ",
        submitRatings: "Derecelendirmeleri Gönder",
        calculateScores: "Puanları Hesapla",
        over: "Tur Bitti",
        finalScores: "Nihai Puanlar",
        playAgain: "Tekrar Oyna",
        waitingFHTS: "${hostName} bir sonraki turu başlatması bekleniyor...",
    },
    ja: {
        welcome: "ようこそ！",
        coj: "作成または参加",
        yourName: "あなたの名前",
        createGame: "新しいゲームを作成",
        or: "または",
        gameCode: "ゲームコード",
        joinGame: "コードで参加",
        loading: "ゲームを読み込み中...",
        noPlayers: "まだプレイヤーがいません",
        lobby: "ロビー",
        shareCode: "友達とこのコードを共有してゲームに参加してください",
        waitingForHostText: "ロビーホストがゲームを開始するのを待っています。",
        startGame: "ゲームを開始",
        youAreTheHost: "あなたがホストです",
        givePrompt: "プレイヤーにプロンプトを与えてください",
        setTheme: "テーマを設定",
        waitingForTheme: "${hostName} がテーマを設定するのを待っています...",
        themeSet: "テーマ: '${data.theme}'",
        waitingForSubmit: "プレイヤーが画像を提出するのを待っています...",
        submit: "${submittedPlayers} / ${totalPlayers} 提出済み",
        submitted: "画像を提出しました。他のプレイヤーを待っています...",
        submitBtn: "画像を提出",
        guessWho: "誰がこの画像を提出したか当てて",
        pSelect: "プレイヤーを選択",
        lockIn: "推測を確定",
        guessing: "${hostName} が推測しています...",
        rate: "プレイヤーが画像を評価するのを待っています",
        rated: "評価ありがとうございます！",
        youRate: "お気に入りの画像を評価してください",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "正解",
        nah: "不正解",
        submitRatings: "評価を送信",
        calculateScores: "スコアを計算",
        over: "ラウンド終了",
        finalScores: "最終スコア",
        playAgain: "もう一度プレイ",
        waitingFHTS: "${hostName} が次のラウンドを開始するのを待っています...",
    },
    ko: {
        welcome: "환영합니다!",
        coj: "생성 또는 참여",
        yourName: "당신의 이름",
        createGame: "새 게임 만들기",
        or: "또는",
        gameCode: "게임 코드",
        joinGame: "코드로 참여하기",
        loading: "게임 로딩 중...",
        noPlayers: "아직 플레이어가 없습니다",
        lobby: "로비",
        shareCode: "친구들과 이 코드를 공유하여 게임에 참여하세요",
        waitingForHostText: "로비 호스트가 게임을 시작하기를 기다리는 중입니다.",
        startGame: "게임 시작",
        youAreTheHost: "당신이 호스트입니다",
        givePrompt: "플레이어에게 프롬프트를 주세요",
        setTheme: "테마 설정",
        waitingForTheme: "${hostName} 님의 테마 설정을 기다리는 중...",
        themeSet: "테마: '${data.theme}'",
        waitingForSubmit: "플레이어들이 이미지를 제출하기를 기다리는 중...",
        submit: "${submittedPlayers} / ${totalPlayers} 제출됨",
        submitted: "이미지를 제출했습니다. 다른 사람들을 기다리는 중...",
        submitBtn: "이미지 제출",
        guessWho: "누가 이 이미지를 제출했는지 맞춰보세요",
        pSelect: "플레이어 선택",
        lockIn: "추측 잠금",
        guessing: "${hostName} 님이 추측 중...",
        rate: "플레이어들이 이미지를 평가하기를 기다리는 중",
        rated: "평가해 주셔서 감사합니다!",
        youRate: "가장 좋아하는 이미지를 평가해 주세요",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "정답",
        nah: "오답",
        submitRatings: "평가 제출",
        calculateScores: "점수 계산",
        over: "라운드 종료",
        finalScores: "최종 점수",
        playAgain: "다시 플레이",
        waitingFHTS: "${hostName} 님이 다음 라운드를 시작하기를 기다리는 중...",
    },
    hi: {
        welcome: "स्वागत है!",
        coj: "बनाएं या शामिल हों",
        yourName: "आपका नाम",
        createGame: "नया खेल बनाएं",
        or: "या",
        gameCode: "खेल कोड",
        joinGame: "कोड से शामिल हों",
        loading: "खेल लोड हो रहा है...",
        noPlayers: "अभी तक कोई खिलाड़ी नहीं",
        lobby: "लॉबी",
        shareCode: "खेल में शामिल होने के लिए इस कोड को अपने दोस्तों के साथ साझा करें",
        waitingForHostText: "लॉबी होस्ट के खेल शुरू करने का इंतजार है।",
        startGame: "खेल शुरू करें",
        youAreTheHost: "आप होस्ट हैं",
        givePrompt: "खिलाड़ियों को एक संकेत दें",
        setTheme: "एक थीम सेट करें",
        waitingForTheme: "${hostName} के थीम सेट करने का इंतजार है...",
        themeSet: "थीम: '${data.theme}'",
        waitingForSubmit: "खिलाड़ियों के अपनी तस्वीरें सबमिट करने का इंतजार है...",
        submit: "${submittedPlayers} / ${totalPlayers} सबमिट किए गए",
        submitted: "आपने अपनी तस्वीर सबमिट कर दी है, दूसरों का इंतजार है...",
        submitBtn: "तस्वीर सबमिट करें",
        guessWho: "अनुमान लगाएं कि यह तस्वीर किसने सबमिट की है",
        pSelect: "एक खिलाड़ी चुनें",
        lockIn: "अपना अनुमान लॉक करें",
        guessing: "${hostName} अनुमान लगा रहा है...",
        rate: "खिलाड़ियों के तस्वीरों को रेट करने का इंतजार है",
        rated: "रेटिंग के लिए धन्यवाद!",
        youRate: "अपनी पसंदीदा तस्वीर को रेट करें",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "सही",
        nah: "गलत",
        submitRatings: "रेटिंग सबमिट करें",
        calculateScores: "स्कोर की गणना करें",
        over: "राउंड खत्म",
        finalScores: "अंतिम स्कोर",
        playAgain: "फिर से खेलें",
        waitingFHTS: "${hostName} के अगले राउंड शुरू करने का इंतजार है...",
    },
    ar: {
        welcome: "أهلا وسهلا!",
        coj: "إنشاء أو الانضمام",
        yourName: "اسمك",
        createGame: "إنشاء لعبة جديدة",
        or: "أو",
        gameCode: "رمز اللعبة",
        joinGame: "الانضمام بالرمز",
        loading: "جارٍ تحميل اللعبة...",
        noPlayers: "لا يوجد لاعبون بعد",
        lobby: "الردهة",
        shareCode: "شارك هذا الرمز مع أصدقائك للانضمام إلى اللعبة",
        waitingForHostText: "في انتظار مضيف الردهة لبدء اللعبة.",
        startGame: "بدء اللعبة",
        youAreTheHost: "أنت المضيف",
        givePrompt: "أعط تلميحًا للاعبين",
        setTheme: "تعيين سمة",
        waitingForTheme: "في انتظار ${hostName} لتعيين سمة...",
        themeSet: "السمة: '${data.theme}'",
        waitingForSubmit: "في انتظار اللاعبين لتقديم صورهم...",
        submit: "${submittedPlayers} / ${totalPlayers} تم التقديم",
        submitted: "لقد قدمت صورتك، في انتظار الآخرين...",
        submitBtn: "إرسال الصورة",
        guessWho: "خمن من قدم هذه الصورة",
        pSelect: "اختر لاعبًا",
        lockIn: "تأكيد تخمينك",
        guessing: "${hostName} يخمن...",
        rate: "في انتظار اللاعبين لتقييم الصور",
        rated: "شكرا للتقييم!",
        youRate: "قيم صورتك المفضلة",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "صحيح",
        nah: "خطأ",
        submitRatings: "إرسال التقييمات",
        calculateScores: "حساب النقاط",
        over: "انتهت الجولة",
        finalScores: "النتائج النهائية",
        playAgain: "العب مرة أخرى",
        waitingFHTS: "في انتظار ${hostName} لبدء الجولة التالية...",
    },
    zn: { // Assuming 'zn' is simplified Chinese, identical to 'mc' for consistency
        welcome: "欢迎！",
        coj: "创建或加入",
        yourName: "你的名字",
        createGame: "创建新游戏",
        or: "或",
        gameCode: "游戏代码",
        joinGame: "使用代码加入",
        loading: "正在加载游戏...",
        noPlayers: "还没有玩家",
        lobby: "大厅",
        shareCode: "与你的朋友分享此代码以加入游戏",
        waitingForHostText: "等待大厅主持人开始游戏。",
        startGame: "开始游戏",
        youAreTheHost: "你是主持人",
        givePrompt: "给玩家一个提示",
        setTheme: "设置主题",
        waitingForTheme: "等待 ${hostName} 设置主题...",
        themeSet: "主题: '${data.theme}'",
        waitingForSubmit: "等待玩家提交他们的图片...",
        submit: "${submittedPlayers} / ${totalPlayers} 已提交",
        submitted: "您已提交您的图片，等待其他人...",
        submitBtn: "提交图片",
        guessWho: "猜猜谁提交了这张图片",
        pSelect: "选择一个玩家",
        lockIn: "锁定你的猜测",
        guessing: "${hostName} 正在猜测...",
        rate: "等待玩家评价图片",
        rated: "感谢您的评价！",
        youRate: "评价您最喜欢的图片",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "正确",
        nah: "错误",
        submitRatings: "提交评分",
        calculateScores: "计算分数",
        over: "回合结束",
        finalScores: "最终得分",
        playAgain: "再玩一次",
        waitingFHTS: "等待 ${hostName} 开始下一轮...",
    },
    mac: { // All words replaced by "Брат" except for variables
        welcome: "Брат!",
        coj: "Брат брат",
        yourName: "Брат брат",
        createGame: "Брат брат брат",
        or: "БРАТ",
        gameCode: "Брат брат",
        joinGame: "Брат брат брат",
        loading: "Брат брат...",
        noPlayers: "Брат брат брат",
        lobby: "Брат",
        shareCode: "Брат брат брат брат брат брат брат брат брат брат",
        waitingForHostText: "Брат брат брат брат брат брат брат брат.",
        startGame: "Брат брат",
        youAreTheHost: "Брат брат брат",
        givePrompt: "Брат брат брат брат",
        setTheme: "Брат брат",
        waitingForTheme: "Брат брат ${hostName} брат брат брат...",
        themeSet: "Брат: '${data.theme}'",
        waitingForSubmit: "Брат брат брат брат брат брат брат...",
        submit: "${submittedPlayers} / ${totalPlayers} брат",
        submitted: "Брат брат брат брат брат брат брат...",
        submitBtn: "Брат брат",
        guessWho: "Брат брат брат брат брат",
        pSelect: "Брат брат",
        lockIn: "Брат брат брат",
        guessing: "${hostName} брат...",
        rate: "Брат брат брат брат брат брат",
        rated: "Брат брат брат!",
        youRate: "Брат брат брат брат",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "БРАТ",
        nah: "БРАТ",
        submitRatings: "Брат брат",
        calculateScores: "Брат брат",
        over: "Брат брат",
        finalScores: "Брат брат",
        playAgain: "Брат брат",
        waitingFHTS: "Брат брат ${hostName} брат брат брат брат...",
    },
    latn: {
        welcome: "Salve!",
        coj: "Crea aut Iunge",
        yourName: "Tuus Nomen",
        createGame: "Novum Ludum Crea",
        or: "VEL",
        gameCode: "Codex Ludi",
        joinGame: "Iunge cum Codice",
        loading: "Ludum Cargando...",
        noPlayers: "Nulli ludi adhuc",
        lobby: "Locus Conventus",
        shareCode: "Hunc codicem amicis tuis communica ut ludum ineas",
        waitingForHostText: "Exspectans Dominum Loci Conventus ut ludum incipiat.",
        startGame: "Incipe Ludum",
        youAreTheHost: "Tu es Dominus",
        givePrompt: "Da promptum histrionibus",
        setTheme: "Constitue thema",
        waitingForTheme: "Exspectans ${hostName} ut thema constituat...",
        themeSet: "Thema: '${data.theme}'",
        waitingForSubmit: "Exspectans histriones ut imagines suas submittant...",
        submit: "${submittedPlayers} / ${totalPlayers} submissi",
        submitted: "Imaginem tuam submisisti, exspectans alios...",
        submitBtn: "Submitte Imaginem",
        guessWho: "Divina Quis hanc imaginem submisit",
        pSelect: "elige histrionem",
        lockIn: "Obfirma divinatum tuum",
        guessing: "${hostName} divinat...",
        rate: "exspectans histriones ut imagines aestiment",
        rated: "Gratias pro aestimatione!",
        youRate: "Aestima imaginem tuam dilectissimam",
        hostGuessed: '<span class="font-bold">${guessedPlayerName}',
        yay: "RECTE",
        nah: "FALSE",
        submitRatings: "Submitte Aestimationes",
        calculateScores: "Calcula Scopes",
        over: "Circulus Finitus",
        finalScores: "Finales Scopes",
        playAgain: "Ludite iterum",
        waitingFHTS: "Exspectans ${hostName} ut proximum circulum incipiat...",
    }
};